// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gorilla/mux"
	"github.com/multipleton/sa-3/database"
	"github.com/multipleton/sa-3/disks"
	"github.com/multipleton/sa-3/utils"
)

// Injectors from modules.go:

func InitializeApplication(port HttpPortNumber, databaseConfiguration database.DatabaseConfiguration) (*ApiServer, error) {
	router := mux.NewRouter()
	db, err := database.NewDatabaseConnection(databaseConfiguration)
	if err != nil {
		return nil, err
	}
	disksRepository := disks.NewDisksRepository(db)
	disksService := disks.NewDisksService(disksRepository)
	disksController := disks.NewDisksController(disksService)
	v := composeHTTPControllers(disksController)
	apiServer := &ApiServer{
		port:        port,
		router:      router,
		controllers: v,
	}
	return apiServer, nil
}

// modules.go:

func composeHTTPControllers(disksController *disks.DisksController) []utils.HTTPController {
	return []utils.HTTPController{disksController}
}
